# Generated by Django 5.0.7 on 2024-09-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_avatar_darkmode_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkmode',
            name='nav_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
