# Generated by Django 5.0.7 on 2024-09-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_darkmode_nav_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatarid',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='avatar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.avatar'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='darkmode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.darkmode'),
        ),
    ]
