# Generated by Django 5.0.7 on 2024-09-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_avatar_id_alter_avatar_avatarid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='darkmode',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='user',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='avatarid',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='avatarurl',
        ),
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='..\\setting\\static\\setting\\images'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.avatar'),
        ),
        migrations.DeleteModel(
            name='DarkMode',
        ),
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
