# Generated by Django 5.0.7 on 2024-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='avatarid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
